apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: skitest01httpd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: skitest01httpd
  template:
    metadata:
      labels:
        app: skitest01httpd
    spec:
      containers:
      - name: skitest01httpd
        image: skiacr.azurecr.io/httpd:v1
        ports:
        - containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 80
        startupProbe:
          httpGet:
            path: /
            port: 80